version: '3'
services:
  node:
    build: .
    command: npm start
    ports:
      - "5555:5000"
    env_file:
      - .env.prod
    networks:
      - redis-net
    depends_on:
      - redis
    restart: always
  redis:
    image: "redis:alpine"
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    networks: 
      - redis-net
    volumes:
      - redis-data:/data

networks: 
  redis-net:

volumes:
  redis-data:
